---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/pwsh -version
    register: powershell_output
  - name: pwsh --version
    debug:
      msg: '{{ powershell_output.stdout }}'
- hosts: all
  vars:
    powershell_trust:
      - Name: PSGallery
        InstallationPolicy: Trusted
    powershell_install_modules:
      - Name: Az
        Scope: CurrentUser
  roles:
  - role: '{{ playbook_dir }}'
